---
title: Www.Campnerdly.Org
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Your New Jekyll Site
markdown: redcarpet
pygments: true
header: 'Camp Nerdly 7: May 16-18, 2014, Prince William Forest Park'
